### ISSUE TITLE
Discord.js version number

### ISSUE THREAD

**Issue by Tubaleviao** [Saious119/Discord-Bots#6]
I tried ou the code but it looks like the voiceChannel.join() function does not exist in the latest version of the discord.js npm package. What version do we need to use to have this code running? I'm willing to add a package.json so we won't have this issue anymore.

**Comment by Saious119** [comment]
yeah I was trying to bump up to 13, but everything just dies, so I guess I'm staying on 12.5.3 for now. that's listed in the package.json I just push. I'll probably make a dev branch for moving over when people have more voice chat solutions in 13

**Comment by Saious119** [comment]
listed Discord.js 12.5.3 in new package.json
